Repository OkapiLib/OkapiLib, pull requests merged in 2018-09, with the labels that each got.

#196 Issue #195: Add createPtr versions of all the CCF methods
  include/okapi/impl/chassis/controller/chassisControllerFactory.hpp
  src/impl/chassis/controller/chassisControllerFactory.cpp
Labels: enhancement, needs docs

#200 #199: Fix QMass literals namespace
  include/okapi/api/units/QMass.hpp
Labels: bug

#206 RQuantity unary minus operator overload
  include/okapi/api/units/RQuantity.hpp
  test/unitTests.cpp
Labels: enhancement

#208 Throw exception from MotorGroup ctor if no motors are given
  include/okapi/impl/device/motor/motorGroup.hpp
  src/impl/device/motor/motorGroup.cpp
Labels: bug, needs docs

#210 Fix APIC RPM limit
  include/okapi/api/control/async/asyncPosIntegratedController.hpp
  include/okapi/impl/control/async/asyncControllerFactory.hpp
  include/test/tests/api/implMocks.hpp
  src/api/control/async/asyncPosIntegratedController.cpp
  src/api/control/async/asyncVelIntegratedController.cpp
  src/impl/control/async/asyncControllerFactory.cpp
  test/asyncPosIntegratedControllerTests.cpp
  test/implMocks.cpp
Labels: bug, needs docs

#204 Issue #202: Rephrase ChassisModel parameters
  include/okapi/api/chassis/controller/chassisController.hpp
  include/okapi/api/chassis/model/chassisModel.hpp
  include/okapi/api/chassis/model/skidSteerModel.hpp
  include/okapi/api/chassis/model/xDriveModel.hpp
  src/api/chassis/controller/chassisController.cpp
  src/api/chassis/model/skidSteerModel.cpp
  src/api/chassis/model/xDriveModel.cpp
Labels: enhancement, needs docs

#212 Add ADIGyro class
  include/okapi/api.hpp
  include/okapi/impl/device/rotarysensor/adiGyro.hpp
  src/impl/device/rotarysensor/adiGyro.cpp
Labels: enhancement, needs docs

#218 Fix ChassisModel low maximum velocity
  CMakeLists.txt
  include/okapi/api/chassis/model/chassisModel.hpp
  include/okapi/api/chassis/model/skidSteerModel.hpp
  include/okapi/api/chassis/model/threeEncoderSkidSteerModel.hpp
  include/okapi/api/chassis/model/xDriveModel.hpp
  src/api/chassis/controller/chassisController.cpp
  src/api/chassis/model/chassisModel.cpp
  src/api/chassis/model/skidSteerModel.cpp
  src/api/chassis/model/xDriveModel.cpp
  test/skidSteerModelTests.cpp
  test/xDriveModelTests.cpp
Labels: bug, needs docs

#231 Motion profile controllers stop when disabled
  src/api/control/async/asyncLinearMotionProfileController.cpp
  src/api/control/async/asyncMotionProfileController.cpp
  test/asyncLinearMotionProfileControllerTests.cpp
  test/asyncMotionProfileControllerTests.cpp
Labels: bug

#229 Override setMaxVelocity in ChassisControllerIntegrated
  include/okapi/api/chassis/controller/chassisController.hpp
  include/okapi/api/chassis/controller/chassisControllerIntegrated.hpp
  include/okapi/api/chassis/model/chassisModel.hpp
  include/okapi/api/control/async/asyncPosIntegratedController.hpp
  include/test/tests/api/implMocks.hpp
  src/api/chassis/controller/chassisControllerIntegrated.cpp
  src/api/control/async/asyncLinearMotionProfileController.cpp
  src/api/control/async/asyncPosIntegratedController.cpp
  test/asyncPosIntegratedControllerTests.cpp
  test/asyncVelIntegratedControllerTests.cpp
  test/chassisControllerIntegratedTests.cpp
  test/chassisControllerPidTest.cpp
  test/implMocks.cpp
Labels: bug, needs docs
