Repository OkapiLib/OkapiLib, pull requests merged in 2018-10, with the labels that each got.

#241 Fix motion profile controllers sometimes segfaulting
  src/api/control/async/asyncLinearMotionProfileController.cpp
  src/api/control/async/asyncMotionProfileController.cpp
Labels: bug

#237 Take another pass at using std::atomic types
  include/okapi/api/chassis/controller/chassisControllerPid.hpp
  include/okapi/api/control/async/asyncLinearMotionProfileController.hpp
  include/okapi/api/control/async/asyncMotionProfileController.hpp
  include/okapi/api/control/async/asyncWrapper.hpp
  src/api/chassis/controller/chassisControllerPid.cpp
  src/api/control/async/asyncLinearMotionProfileController.cpp
  src/api/control/async/asyncMotionProfileController.cpp
  test/asyncPosIntegratedControllerTests.cpp
  test/implMocks.cpp
Labels: bug

#244 AsyncMotionProfileController does not account for external ratio
  include/okapi/api/control/async/asyncMotionProfileController.hpp
  include/okapi/api/device/motor/abstractMotor.hpp
  src/api/control/async/asyncMotionProfileController.cpp
  test/asyncMotionProfileControllerTests.cpp
Labels: bug, needs docs

#247 Make Controller::operator[] return the same ControllerButton instance
  include/okapi/impl/device/controller.hpp
  src/impl/device/controller.cpp
Labels: enhancement, needs docs

#251 Update kernel
  firmware/libpros.a
  include/api.h
  include/okapi/api/device/motor/abstractMotor.hpp
  include/okapi/impl/device/controller.hpp
  include/okapi/impl/device/motor/motor.hpp
  include/okapi/impl/device/motor/motorGroup.hpp
  include/pros/adi.h
  include/pros/adi.hpp
  include/pros/misc.h
  include/pros/misc.hpp
  include/pros/motors.h
  include/pros/motors.hpp
  include/pros/rtos.h
  include/pros/rtos.hpp
  project.pros
  src/impl/device/adiUltrasonic.cpp
  src/impl/device/controller.cpp
  src/opcontrol.cpp
Labels: enhancement, needs docs

#245 Issue #234: Pass shared_ptr by const ref
  include/okapi/api/chassis/controller/chassisController.hpp
  include/okapi/api/chassis/controller/chassisControllerIntegrated.hpp
  include/okapi/api/chassis/controller/chassisControllerPid.hpp
  include/okapi/api/chassis/model/skidSteerModel.hpp
  include/okapi/api/chassis/model/threeEncoderSkidSteerModel.hpp
  include/okapi/api/chassis/model/xDriveModel.hpp
  include/okapi/api/control/async/asyncLinearMotionProfileController.hpp
  include/okapi/api/control/async/asyncMotionProfileController.hpp
  include/okapi/api/control/async/asyncPosIntegratedController.hpp
  include/okapi/api/control/async/asyncPosPidController.hpp
  include/okapi/api/control/async/asyncVelIntegratedController.hpp
  include/okapi/api/control/async/asyncVelPidController.hpp
  include/okapi/api/control/async/asyncWrapper.hpp
  include/okapi/api/control/iterative/iterativeMotorVelocityController.hpp
  include/okapi/api/control/util/pidTuner.hpp
  include/okapi/api/filter/composableFilter.hpp
  include/okapi/api/filter/velMath.hpp
  src/api/chassis/controller/chassisController.cpp
  src/api/chassis/controller/chassisControllerIntegrated.cpp
  src/api/chassis/controller/chassisControllerPid.cpp
  src/api/chassis/model/skidSteerModel.cpp
  src/api/chassis/model/threeEncoderSkidSteerModel.cpp
  src/api/chassis/model/xDriveModel.cpp
  src/api/control/async/asyncLinearMotionProfileController.cpp
  src/api/control/async/asyncMotionProfileController.cpp
  src/api/control/async/asyncPosIntegratedController.cpp
  src/api/control/async/asyncPosPidController.cpp
  src/api/control/async/asyncVelIntegratedController.cpp
  src/api/control/async/asyncVelPidController.cpp
  src/api/control/iterative/iterativeMotorVelocityController.cpp
  src/api/control/util/pidTuner.cpp
  src/api/filter/composableFilter.cpp
  src/api/filter/velMath.cpp
Labels: enhancement, needs docs

#230 Refactor most factories to be smaller
  include/okapi/impl/chassis/controller/chassisControllerFactory.hpp
  include/okapi/impl/control/async/asyncControllerFactory.hpp
  include/okapi/impl/control/util/pidTunerFactory.hpp
  include/okapi/impl/device/controller.hpp
  src/impl/chassis/controller/chassisControllerFactory.cpp
  src/impl/control/async/asyncControllerFactory.cpp
  src/impl/control/util/pidTunerFactory.cpp
  src/impl/device/controller.cpp
Labels: enhancement, needs docs

#255 Add TimeUtilFactory method for SettledUtil
  include/okapi/impl/util/timeUtilFactory.hpp
  src/impl/util/timeUtilFactory.cpp
Labels: enhancement, needs docs

#257 Add a way to mirror ChassisController turns
  include/okapi/api/chassis/controller/chassisController.hpp
  include/okapi/api/util/mathUtil.hpp
  src/api/chassis/controller/chassisController.cpp
  src/api/chassis/controller/chassisControllerIntegrated.cpp
  src/api/chassis/controller/chassisControllerPid.cpp
  src/opcontrol.cpp
  test/chassisControllerIntegratedTests.cpp
  test/chassisControllerPidTest.cpp
Labels: enhancement, needs docs
