Repository OkapiLib/OkapiLib, pull requests merged in 2019-04, with the labels that each got.

#361 Feature/v3.3.13
  include/okapi/api/filter/velMath.hpp
  test/filterTests.cpp
Labels: bug

#359 Issue #358: Implement saving/loading paths
  include/okapi/api/control/async/asyncMotionProfileController.hpp
  src/api/control/async/asyncMotionProfileController.cpp
  test/asyncMotionProfileControllerTests.cpp
Labels: enhancement, needs docs

#363 Change motion profile DT to 10 milliseconds
  src/api/control/async/asyncLinearMotionProfileController.cpp
  src/api/control/async/asyncMotionProfileController.cpp
Labels: enhancement

#365 Add derived telemetry functions getPositionError and getVelocityError
  include/okapi/api/device/motor/abstractMotor.hpp
  src/api/device/motor/abstractMotor.cpp
Labels: enhancement, needs docs
