Repository OkapiLib/OkapiLib, pull requests merged in 2019-01, with the labels that each got.

#300 Cherry-pick 04fcb54c77ca43e13790234058d2029be665ab81
  src/api/control/iterative/iterativePosPidController.cpp
  test/iterativePosPIDControllerTests.cpp
  test/iterativeVelPIDControllerTests.cpp
Labels: bug

#301 Merge develop for next release
  CONTRIBUTING.md
Labels: enhancement

#307 Fix ADI update rate
  include/okapi/api/util/mathUtil.hpp
Labels: bug

#311 Fix Motor constructor setting gearset incorrectly
  src/impl/device/motor/motor.cpp
  src/test/chassisControllerFactoryIntegrationTests.cpp
Labels: bug

#315 Change the default Motor gearset to green
  include/okapi/impl/device/motor/motor.hpp
  src/impl/device/motor/motor.cpp
Labels: enhancement

#314 Fix CCPID turns
  src/api/chassis/controller/chassisControllerPid.cpp
Labels: bug

#318 Fix `MotorGroup::controllerSet`
  src/impl/device/motor/motorGroup.cpp
Labels: bug

#319 Fix #293 and add tests for it
  src/api/chassis/model/skidSteerModel.cpp
  src/api/chassis/model/xDriveModel.cpp
  test/skidSteerModelTests.cpp
  test/xDriveModelTests.cpp
Labels: bug

#323 Derive ControllerInput<bool> for AbstractButton
  include/okapi/api/device/button/abstractButton.hpp
  src/api/device/button/abstractButton.cpp
Labels: enhancement, needs docs
